# Generated by Django 3.0.3 on 2020-02-25 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('team', models.CharField(default='', max_length=100)),
                ('years', models.CharField(default='', max_length=100)),
                ('college', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('birthdate', models.CharField(default='', max_length=100)),
                ('debut', models.CharField(default='', max_length=100)),
                ('height', models.CharField(default='', max_length=100)),
                ('weight', models.CharField(default='', max_length=100)),
                ('number', models.CharField(default='', max_length=100)),
                ('active', models.CharField(default='', max_length=100)),
                ('position', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=250)),
                ('url', models.CharField(default='', max_length=250)),
                ('picture', models.CharField(default='', max_length=250)),
                ('conference', models.CharField(default='', max_length=250)),
                ('division', models.CharField(default='', max_length=250)),
                ('favorite', models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
