# Generated by Django 3.0.3 on 2020-02-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200220_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='stadium',
        ),
    ]
