# Generated by Django 3.0.3 on 2020-02-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_team_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='conference',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='team',
            name='url',
            field=models.CharField(default='', max_length=250),
        ),
    ]
