# Generated by Django 3.0.3 on 2020-02-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200224_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='lastname',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(default='', max_length=100),
        ),
    ]
