# Generated by Django 3.0.3 on 2020-02-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200224_1247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
