# Generated by Django 3.0.3 on 2020-02-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200224_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
