# Generated by Django 3.0.3 on 2020-02-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('team', models.CharField(default='', max_length=100)),
                ('years', models.CharField(default='', max_length=100)),
                ('college', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('birthdate', models.CharField(default='', max_length=100)),
                ('debut', models.CharField(default='', max_length=100)),
                ('height', models.CharField(default='', max_length=100)),
                ('weight', models.CharField(default='', max_length=100)),
                ('number', models.CharField(default='', max_length=100)),
                ('active', models.CharField(default='', max_length=100)),
                ('position', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
