# Generated by Django 3.0.3 on 2020-02-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_player'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='Baller',
        ),
    ]
