# Generated by Django 3.0.2 on 2020-01-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=25, null=True)),
                ('hour', models.CharField(max_length=25, null=True)),
                ('vteam', models.CharField(max_length=25, null=True)),
                ('hteam', models.CharField(max_length=25, null=True)),
                ('game_type', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
