# Generated by Django 2.2 on 2020-03-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200309_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='arena',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
